
import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper"; 
export const metadata: Metadata = {
  title: "Social Media",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="antialiased">{children}</body>
      </html>
      </SessionWrapper>
  );
}
