# Generated by Django 5.1.3 on 2024-11-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pins',
            field=models.ManyToManyField(blank=True, related_name='pinned_by', to='core.pin'),
        ),
    ]
