# Generated by Django 5.1.3 on 2025-02-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_picture',
            field=models.URLField(blank=True),
        ),
    ]
