# Generated by Django 5.1.3 on 2025-02-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_background_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.URLField(),
        ),
    ]
