# Generated by Django 5.1.3 on 2025-02-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='created_by', to='core.board'),
        ),
    ]
