# Generated by Django 5.1.3 on 2025-02-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_boards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='boards',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pins',
        ),
    ]
