# Generated by Django 5.1.3 on 2025-02-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_boards_remove_customuser_pins'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='created_by', to='core.board'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pins',
            field=models.ManyToManyField(blank=True, related_name='pinned_by', to='core.pin'),
        ),
    ]
